spring:
  profiles:
    active: dev



server:
  port: 8080
  servlet:
    context-path: /admin


mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml


jwt:
  JWTHeader: Authorization


