spring:
  datasource:
    druid:
      url:  jdbc:mysql://localhost:3306/dbook
      driver-class-name: com.mysql.cj.jdbc.Driver
      username:  root
      password:  1234
      initial-size:  10
      max-active:  50
      min-idle:  10
      max-wait:  60000
      pool-prepared-statements:  true
      max-pool-prepared-statement-per-connection-size:  20
      validation-query:  SELECT 1 FROM DUAL
      test-on-borrow:  false
      test-on-return:  false
      test-while-idle:  true
      time-between-eviction-runs-millis:  60000
#      filters:  stat,wall